(cl:defpackage motoman_viz_msgs-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<BOUNDINGBOXARRAY>"
   "BOUNDINGBOXARRAY"
   "<EUCLIDEANLINKTRAJECTORY>"
   "EUCLIDEANLINKTRAJECTORY"
   "<EUCLIDEANLINKTRAJECTORYPOINT>"
   "EUCLIDEANLINKTRAJECTORYPOINT"
  ))

