// Generated by gencpp from file motoman_viz_msgs/EuclideanLinkTrajectory.msg
// DO NOT EDIT!


#ifndef MOTOMAN_VIZ_MSGS_MESSAGE_EUCLIDEANLINKTRAJECTORY_H
#define MOTOMAN_VIZ_MSGS_MESSAGE_EUCLIDEANLINKTRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <motoman_viz_msgs/EuclideanLinkTrajectoryPoint.h>

namespace motoman_viz_msgs
{
template <class ContainerAllocator>
struct EuclideanLinkTrajectory_
{
  typedef EuclideanLinkTrajectory_<ContainerAllocator> Type;

  EuclideanLinkTrajectory_()
    : header()
    , link_names()
    , points()  {
    }
  EuclideanLinkTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , link_names(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _link_names_type;
  _link_names_type link_names;

   typedef std::vector< ::motoman_viz_msgs::EuclideanLinkTrajectoryPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::motoman_viz_msgs::EuclideanLinkTrajectoryPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct EuclideanLinkTrajectory_

typedef ::motoman_viz_msgs::EuclideanLinkTrajectory_<std::allocator<void> > EuclideanLinkTrajectory;

typedef boost::shared_ptr< ::motoman_viz_msgs::EuclideanLinkTrajectory > EuclideanLinkTrajectoryPtr;
typedef boost::shared_ptr< ::motoman_viz_msgs::EuclideanLinkTrajectory const> EuclideanLinkTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator1> & lhs, const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.link_names == rhs.link_names &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator1> & lhs, const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motoman_viz_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3441963936bb9e1e795c3899e3694140";
  }

  static const char* value(const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3441963936bb9e1eULL;
  static const uint64_t static_value2 = 0x795c3899e3694140ULL;
};

template<class ContainerAllocator>
struct DataType< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motoman_viz_msgs/EuclideanLinkTrajectory";
  }

  static const char* value(const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string[] link_names\n"
"EuclideanLinkTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: motoman_viz_msgs/EuclideanLinkTrajectoryPoint\n"
"geometry_msgs/Pose[] pose\n"
"duration time_from_start\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.link_names);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EuclideanLinkTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motoman_viz_msgs::EuclideanLinkTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "link_names[]" << std::endl;
    for (size_t i = 0; i < v.link_names.size(); ++i)
    {
      s << indent << "  link_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.link_names[i]);
    }
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::motoman_viz_msgs::EuclideanLinkTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOMAN_VIZ_MSGS_MESSAGE_EUCLIDEANLINKTRAJECTORY_H
